/// Uzbekistan administrative regions (viloyatlar) → districts/cities (tumanlar).
/// Used by the job-posting form cascading location dropdowns.
const Map<String, List<String>> uzbekistanRegions = {
  'Toshkent shahri': [
    'Bektemir',
    'Chilonzor',
    'Hamza',
    'Mirzo Ulug\'bek',
    'Mirobod',
    'Olmazor',
    'Sergeli',
    'Shayxontohur',
    'Uchtepa',
    'Yakkasaroy',
    'Yunusobod',
  ],
  'Toshkent viloyati': [
    'Angren',
    'Bekobod',
    'Bo\'stonliq',
    'Bo\'ka',
    'Chirchiq',
    'Chinoz',
    'Ohangaron',
    'Parkent',
    'Piskent',
    'Qibray',
    'Toshloq',
    'Urtachirchiq',
    'Yuqorichirchiq',
    'Zangiota',
  ],
  'Andijon': [
    'Andijon',
    'Asaka',
    'Baliqchi',
    'Bo\'z',
    'Buloqboshi',
    'Izboskan',
    'Jalolquduq',
    'Marhamat',
    'Oltinko\'l',
    'Paxtaobod',
    'Shahrixon',
    'Ulug\'nor',
    'Xo\'jaobod',
  ],
  'Farg\'ona': [
    'Beshariq',
    'Bog\'dod',
    'Buvayda',
    'Dang\'ara',
    'Farg\'ona',
    'Furqat',
    'Oltiariq',
    'Quva',
    'Rishton',
    'So\'x',
    'Toshloq',
    'Uchko\'prik',
    'Yozyovon',
  ],
  'Namangan': [
    'Chortoq',
    'Chust',
    'Kosonsoy',
    'Mingbuloq',
    'Namangan',
    'Norin',
    'Pop',
    'To\'raqo\'rg\'on',
    'Uychi',
    'Yangidaryo',
  ],
  'Samarqand': [
    'Bulung\'ur',
    'Ishtixon',
    'Jomboy',
    'Kattaqo\'rg\'on',
    'Narpay',
    'Nurobod',
    'Oqdaryo',
    'Pastdarg\'om',
    'Payariq',
    'Samarqand',
    'Tayloq',
    'Urgut',
  ],
  'Buxoro': [
    'Buxoro',
    'G\'ijduvon',
    'Jondor',
    'Kogon',
    'Olot',
    'Peshku',
    'Romitan',
    'Shofirkon',
    'Vobkent',
    'Qorovulbozor',
  ],
  'Navoiy': [
    'Konimex',
    'Navbahor',
    'Navoiy',
    'Nurota',
    'Qiziltepa',
    'Tomdi',
    'Uchquduq',
    'Xatirchi',
  ],
  'Qashqadaryo': [
    'Chiroqchi',
    'Dehqonobod',
    'G\'uzor',
    'Kasbi',
    'Kitob',
    'Koson',
    'Mirishkor',
    'Muborak',
    'Nishon',
    'Qamashi',
    'Qarshi',
    'Shahrisabz',
    'Yakkabog\'',
  ],
  'Surxondaryo': [
    'Angor',
    'Boysun',
    'Denov',
    'Jarqo\'rg\'on',
    'Muzrabot',
    'Oltinsoy',
    'Qiziriq',
    'Sariosiyo',
    'Sherobod',
    'Sho\'rchi',
    'Termiz',
    'Uzun',
  ],
  'Jizzax': [
    'Arnasoy',
    'Baxmal',
    'Do\'stlik',
    'Forish',
    'G\'allaorol',
    'Jizzax',
    'Pakhtakor',
    'Yangiobod',
    'Zafarobod',
    'Zarbdor',
    'Zomin',
  ],
  'Sirdaryo': [
    'Boyovut',
    'Guliston',
    'Mirzaobod',
    'Oqoltin',
    'Sardoba',
    'Sayxunobod',
    'Sirdaryo',
    'Xovos',
  ],
  'Xorazm': [
    'Bog\'ot',
    'Gurlan',
    'Hazorasp',
    'Xiva',
    'Ko\'hna Urganch',
    'Pitnak',
    'Shovot',
    'Urganch',
    'Yangiariq',
    'Yangibozor',
  ],
  'Qoraqalpog\'iston': [
    'Amudaryo',
    'Beruniy',
    'Chimboy',
    'Ellikkala',
    'Kegeyli',
    'Mo\'ynoq',
    'Nukus',
    'Qanlikol',
    'Qorao\'zak',
    'Shumanay',
    'Taxiatosh',
    'To\'rtko\'l',
    'Xo\'jayli',
  ],
};

/// Returns the districts/cities for [region], or empty list if not found.
List<String> districtsFor(String? region) =>
    region == null ? const [] : (uzbekistanRegions[region] ?? const []);
