/**
 * Admin panel copy — Uzbek only, by design. The panel is an internal tool for
 * the technical team, so it deliberately lives outside next-intl (no ru/en
 * catalogs, no parity-test surface). Repeated labels live here; one-off page
 * copy may stay inline in the page components.
 */
export const adminStrings = {
  brand: "Yollla Admin",
  panelTitle: "Boshqaruv paneli",
  demoMode: "Demo rejim — Supabase sozlanmagan, ma'lumotlar namunaviy",
  loadError: "Ma'lumotlarni yuklab bo'lmadi",
  loadErrorHint: "Keyinroq qayta urinib ko'ring yoki konsol loglarini tekshiring.",
  readKeyMissing: "O'qish kaliti sozlanmagan",
  readKeyMissingHint:
    "SUPABASE_SERVICE_ROLE_KEY o'rnatilmagan — ro'yxatlar shu kalitsiz o'qilmaydi.",
  comingSoon: "Tez kunda",
  save: "Saqlash",
  cancel: "Bekor qilish",
  confirm: "Tasdiqlash",
  confirmAsk: "Ishonchingiz komilmi?",
  search: "Qidirish",
  empty: "Hech narsa topilmadi",
  prev: "Oldingi",
  next: "Keyingi",
  actionFailed: "Amal bajarilmadi — qaytadan urinib ko'ring",
  mod: {
    reasonPlaceholder: "Sabab (ixtiyoriy)",
    block: "Bloklash",
    unblock: "Blokdan chiqarish",
    suspend: "To'xtatish",
    unsuspend: "Tiklash",
    hide: "Yashirish",
    show: "Ko'rsatish",
    verify: "Tasdiqlash",
    blocked: "Bloklangan",
    suspended: "To'xtatilgan",
    hidden: "Yashirilgan",
    active: "Faol",
    verified: "Tasdiqlangan",
    unverified: "Tasdiqlanmagan",
    seeker: "Ish izlovchi",
    employer: "Ish beruvchi",
    companyReviews: "Kompaniya sharhlari",
    workerReviews: "Ishchi sharhlari",
    methodLegalEntity: "Yuridik shaxs",
    methodLicensedAgency: "Litsenziyali agentlik",
    methodIdDocument: "Hujjat bo'yicha",
    methodManual: "Qo'lda",
    admin: "Administrator",
    makeAdmin: "Admin qilish",
    revokeAdmin: "Administratordan olib tashlash",
  },
  nav: {
    groups: {
      overview: "Boshqaruv",
      moderation: "Moderatsiya",
      content: "Kontent",
      finance: "Moliya",
      system: "Tizim",
    },
    dashboard: "Dashboard",
    users: "Foydalanuvchilar",
    companies: "Kompaniyalar",
    jobs: "E'lonlar",
    reviews: "Sharhlar",
    categories: "Kategoriyalar",
    telegramChannels: "Telegram kanallar",
    products: "Mahsulotlar",
    blog: "Blog",
    wallet: "Hamyon",
    orders: "Buyurtmalar",
    broadcast: "Xabarnoma",
    settings: "Sozlamalar",
    audit: "Jurnal",
  },
  categories: {
    newTitle: "Yangi kategoriya",
    editTitle: "Tahrirlash",
    name: "Nomi",
    slug: "Slug",
    icon: "Ikonka (emoji)",
    sortOrder: "Tartib raqami",
    active: "Faol",
    inactive: "Faol emas",
    activate: "Faollashtirish",
    deactivate: "Faolsizlantirish",
    add: "Qo'shish",
    saveChanges: "Saqlash",
    bannerUrl: "Banner rasm havolasi",
  },
  telegramChannels: {
    newTitle: "Yangi kanal biriktirish",
    editTitle: "Tahrirlash",
    category: "Kategoriya",
    region: "Viloyat",
    allRegions: "Barcha viloyatlar",
    chatId: "Kanal (@username yoki chat_id)",
    title: "Nomi (ixtiyoriy)",
    active: "Faol",
    inactive: "Faol emas",
    activate: "Faollashtirish",
    deactivate: "Faolsizlantirish",
    add: "Qo'shish",
    saveChanges: "Saqlash",
    hint:
      "Botni kanalga admin qilib qo'shing, so'ng shu yerda kategoriya va viloyat bo'yicha " +
      "biriktiring — yangi vakansiya ochilganda avtomatik shu kanalga post qilinadi. " +
      "Viloyat tanlanmasa, bu kategoriyaning barcha viloyatlari uchun zaxira kanal bo'ladi.",
  },
  settings: {
    bannerTitle: "Sayt e'loni (banner)",
    bannerHint:
      "Yoqilganda sayt tepasida barcha sahifalarda ko'rinadi — texnik ishlar " +
      "yoki muhim xabar uchun. Bo'sh matn — banner ko'rinmaydi.",
    enabled: "Yoqilgan",
    message: "Matn",
    tone: "Ko'rinishi",
    toneInfo: "Oddiy (ko'k)",
    toneWarning: "Ogohlantirish (sariq)",
    save: "Saqlash",
    saved: "Saqlandi",
  },
  broadcast: {
    title: "Xabar sarlavhasi",
    body: "Xabar matni",
    audience: "Kimga",
    audienceAll: "Barcha foydalanuvchilar",
    audienceSeekers: "Ish izlovchilar",
    audienceEmployers: "Ish beruvchilar",
    city: "Shahar (ixtiyoriy)",
    cityHint: "Bo'sh qoldirilsa — barcha shaharlar",
    send: "Yuborish",
    sentOne: "Xabar yuborildi",
    sentCount: "ta foydalanuvchiga yuborildi",
    reach: "Qamrov",
    hint:
      "Xabar ilova ichidagi bildirishnoma sifatida yetkaziladi va (ulangan bo'lsa) " +
      "Telegram/push orqali ham boradi. Bir marta yuborishda eng ko'pi 5000 kishi — " +
      "kattaroq bo'lsa shahar bo'yicha toraytiring.",
  },
  finance: {
    company: "Kompaniya",
    amount: "Summa",
    status: "Holat",
    kind: "Turi",
    description: "Izoh",
    created: "Yaratilgan",
    pending: "Kutilmoqda",
    completed: "Tugallangan",
    cancelled: "Bekor qilingan",
    paid: "To'langan",
    refunded: "Qaytarilgan",
    approve: "Tasdiqlash",
    reject: "Bekor qilish",
    markPaid: "To'langan deb belgilash",
    refund: "Qaytarish",
    kindTopup: "To'ldirish",
    kindSpend: "Sarflangan",
    kindRefund: "Qaytarilgan",
    kindBonus: "Bonus",
    product: "Mahsulot",
    price: "Narxi (so'm)",
    duration: "Muddati (kun)",
    products: "Mahsulotlar narxi",
  },
} as const;
